# Збільшення гучності на 2% при прокручуванні праворуч
KEY_VOLUMEUP    1      /usr/bin/mpc volume +2

# Зменшення гучності на 2% при прокручуванні ліворуч
KEY_VOLUMEDOWN  1      /usr/bin/mpc volume -2

# Перемикання Play/Pause при натисканні на кнопку енкодера
KEY_MUTE        1      /usr/bin/mpc toggle

